package core.termsAndConditions;

public class TermsAndConditions_Route_v1 {
    public static final String webTermsAndConditions = "WHEREAS, Company is in the business of providing merchant services and investigative and remedial solutions and related software to online order problems or failed shipments (collectively, the “Services”) under the brand Route;\n" +
            "<br>\n" +
            "<br>WHEREAS, Merchant operates website(s) offering goods for sale via the Internet; and\n" +
            "<br>\n" +
            "<br>WHEREAS, Merchant desires that Company provide Route-branded Services on selected orders on Merchant’s website(s).\n" +
            "<br>\n" +
            "<br>NOW THEREFORE, in consideration of the mutual promises and covenants hereinafter set forth, the sufficiency of which is hereby acknowledged, Company and Merchant agree as follows:\n" +
            "<br>\n" +
            "<br>1.              SERVICES\n" +
            "<br>a.              During the Term of this Agreement, Merchant agrees to;\n" +
            "<br>i.                  Integration.  Offer Company’s Route-branded Services on Merchant’s website(s), to integrate Company’s API, and to place Route Widget, assets and badges on Merchant’s website(s) checkout page(s), order-confirmation page(s) and emailed order receipt(s) for the purpose of offering Company’s Route Services to Merchant’s customers, as more particularly described in and subject to Company’s terms and conditions.\n" +
            "<br>ii.                  Pricing and Availability or Services.  Offer Company's Services on and only on the pricing terms as set forth in Section 3.\n" +
            "<br>b.              During the term of this Agreement and provided that Merchant continues to offer Company’s Route-branded Services, Company agrees to provide the Services to Merchants' customers subject to the terms and conditions of this Agreement.\n" +
            "<br>\n" +
            "<br>3.              PAYMENT\n" +
            "<br>a.              Pricing.    Merchant agrees to set the price of Route Services as per Route agreement per shipment to Customer, according to Customer’s order.\n" +
            "<br>b.              Revenue.  In consideration of the provision of the Route-branded Services by the Company and the rights granted to Merchant under this Agreement, revenues collected on Route Services sales will be paid out as agreed to in Route agreement. \n" +
            "<br>c.              Invoicing.  Revenues generated from sales of Route-branded Services will be tracked by Company through Company's API integration with Merchant’s Websites and/or Merchant’s CRM as set forth in Section 1, above.  Company will provide Merchant an accounting invoice of the Route Services revenues via email.\n" +
            "<br>d.              Revenue Disputes.  Merchant will have 24 hours to dispute the accounting report referenced in Section 3.c., above.  At the expiration of 24 hours, the revenues set forth in the applicable report will be deemed final and payment will be due as provided under Section 3.b.i.\n" +
            "<br>e.              Payment Method.  Merchant hereby agrees that, for the term of this Agreement, Company has the right to withdraw Company's payment from Merchant's bank account as provided in the ACH authorization attached hereto as Exhibit B.\n" +
            "<br>f.               Miscellaneous.  Merchant shall be responsible for all sales, use and excise taxes, and any other similar taxes, duties and charges of any kind imposed by any federal, state or local governmental entity on any amounts payable by or to Merchant under this Agreement; provided, that, in no event shall Merchant pay or be responsible for any taxes, duties or charges imposed on, or with respect to, Company's income, or revenues received under this Agreement.\n" +
            "<br>\n" +
            "<br>4.              NO JOINT VENTURE, PARTNERSHIP OR AGENCY                      Except as specifically provided in this Agreement, nothing in this Agreement shall be construed to create a partnership, joint venture or agency relationship between the parties and neither party will have the power to bind the other or to incur obligations on the other’s behalf without such other party’s prior written consent.\n" +
            "<br>\n" +
            "<br>5.              EXCLUSIVITY                         The parties acknowledge and agree that this Agreement shall not be construed to be a commitment by Company to work exclusively with Merchant regarding Company’s Services. Notwithstanding the foregoing, by signing this Agreement, Merchant represents and warrants that during the Term, Merchant will exclusively provide Services from Company and that it will not provide similar Services from any other company.\n" +
            "<br>\n" +
            "<br>6.              REPRESENTATIONS AND WARRANTIES\n" +
            "<br>a.              By Company.   As part of this Agreement, Company represents and warrants that:\n" +
            "<br>i.                  It has the necessary corporate power and authority to enter, carry out its obligations and to grants the rights conferred under this Agreement.\n" +
            "<br>ii.                  It shall perform the Services:\n" +
            "<br>1.     In accordance with the terms and subject to the conditions set out in this Agreement and any applicable, signed statement of services.\n" +
            "<br>2.     Using commercially-reasonable skill, experience and qualifications.\n" +
            "<br>3.     In a timely, workmanlike and professional manner in accordance with generally recognized industry standards for similar services.\n" +
            "<br>b.              By Merchant. As part of this Agreement, Merchant represents and warrants that:\n" +
            "<br>i.                  It has the necessary corporate power and authority to enter into this Agreement, to carry out its obligations hereunder and to grant the rights herein granted;\n" +
            "<br>ii.                  It will conduct business in a manner that reflects favorably on Company and its Services;\n" +
            "<br>iii.                  It will make no false or misleading representations with respect to Company or its services;\n" +
            "<br>iv.                  It will make no representations, warranties, or guarantees with respect to the specifications, features, or capabilities of Company or its Services that are inconsistent with Company’s Marketing Materials.\n" +
            "<br>c.              Mutual.  EXCEPT AS EXPRESSLY SET FORTH HEREIN, TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, EACH PARTY DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT, AND ANY WARRANTIES ARISING OUT OF COURSE OF DEALING OR USAGE OF TRADE.\n" +
            "<br>\n" +
            "<br>7.              INDEMNIFICATION            For and in consideration of Company’s agreements contained herein, Merchant hereby agrees to indemnify each of Company, and its respective partners, members, managers, affiliates, directors, officers, employees, representatives, and agents (each being an “Indemnified Party”), from, and agrees to defend and hold such Indemnified Party harmless against, any and all losses,  liabilities,  charges,  damages, expenses and fees which may be asserted against such Indemnified Party arising out of, resulting from, or related in any way to a breach of any representation, warranty, covenant or agreement of Merchant contained in or made pursuant to this Agreement, or any facts or circumstances surrounding such a breach.\n" +
            "<br>\n" +
            "<br>8.              LIMITATION OF LIABILITY               IN NO EVENT SHALL COMPANY BE LIABLE TO MERCHANT OR TO ANY THIRD PARTY FOR ANY LOSS OF USE, REVENUE OR PROFIT, OR FOR ANY CONSEQUENTIAL, INCIDENTAL, INDIRECT, EXEMPLARY, SPECIAL OR PUNITIVE DAMAGES WHETHER ARISING OUT OF BREACH OF CONTRACT, TORT (INCLUDING NEGLIGENCE) OR OTHERWISE, REGARDLESS OF WHETHER SUCH DAMAGE WAS FORESEEABLE AND WHETHER OR NOT COMPANY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, AND NOTWITHSTANDING THE FAILURE OF ANY AGREED OR OTHER REMEDY OF ITS ESSENTIAL PURPOSE.  IN NO EVENT SHALL COMPANY'S AGGREGATE LIABILITY ARISING OUT OF OR RELATED TO THIS AGREEMENT, WHETHER ARISING OUT OF OR RELATED TO BREACH OF CONTRACT, TORT (INCLUDING NEGLIGENCE) OR OTHERWISE, EXCEED THE AGGREGATE AMOUNTS PAID OR PAYABLE TO COMPANY UNDER THIS AGREEMENT.\n" +
            "<br>\n" +
            "<br>9.              TERM OF AGREEMENT\n" +
            "<br>a.              Term. The term of this Agreement commences on the date of this Agreement and continues for a period of one (1) year, unless and until terminated as provided under this Agreement (the \"Initial Term\"). Upon expiration of the Initial Term, this Agreement automatically renews for additional successive one (1) year terms unless and until either party provides notice of nonrenewal at least thirty (30) days prior to the end of the then-current term, or unless and until earlier terminated as provided under this Agreement (each a \"Renewal Term\" and together with the Initial Term, the \"Term\").\n" +
            "<br>b.              Termination. In addition to any remedies that may be provided in this Agreement, either party may terminate this Agreement with immediate effect upon notice to the other party, if the other party: (i) fails to pay any amount when due under this Agreement and such failure continues for three (3) days after the other party's receipt of notice of nonpayment; (ii) has not otherwise performed or complied with any of the terms of this Agreement, in whole or in part; or (iii) becomes insolvent, files a petition for bankruptcy or commences or has commenced against it proceedings relating to bankruptcy, receivership, reorganization or assignment for the benefit of creditors.\n" +
            "<br>c.              Effect of Termination. On expiration or termination of this Agreement for any reason and subject to any express provisions set out elsewhere in this Agreement:\n" +
            "<br>i.                  all outstanding amounts payable by Merchant to Company shall immediately become due and payable;\n" +
            "<br>ii.                  all express or implied rights granted pursuant to this Agreement shall immediately cease;\n" +
            "<br>iii.                  Merchant shall cease all use of the services, including without limitation the marks, brands, software widget and other Intellectual Property as set forth in sections 1 and 10 herein;\n" +
            "<br>iv.                  Merchant shall promptly return to company, or, at Company's option, destroy, at Merchant's expense, all records and copies of technical and promotional material, including source code if any, in its possession relating to the services, and of any Confidential Information or Intellectual Property of Company and all copies thereof.\n" +
            "<br>\n" +
            "<br>10.           INTELLECTUAL PROPERTY\n" +
            "<br>a.              General.  Company is and shall be the sole owner of all rights, title, patents, copyrights, trademark and other proprietary rights in connection with its Services and no license is granted, assigned or implied to be granted to Merchant by reason of its use of or access to said Services.  Except as set forth in this Agreement or otherwise expressly agreed to in writing by the parties, nothing in this Agreement will be deemed to grant or assign to either party any ownership rights, license rights, or interests of any kind in the other party’s products, services or technology or in the other party’s intellectual property or proprietary rights.\n" +
            "<br>b.              Marketing Materials.  From time to time, Company will provide Merchant with its standard marketing and sales literature that it customarily uses to promote Company’s Services (“Marketing Materials”). Merchant will use Company’s Marketing Materials solely for the purposes of this Agreement. Merchant may not copy, modify, alter, adapt or create derivative works based on Company’s Marketing Materials.\n" +
            "<br>c.              Use Restrictions. Except as this Agreement expressly permits Merchant shall not, and shall not permit any other Person to:\n" +
            "<br>i.                  copy the Company's Services, Intellectual Property or marketing material, in whole or in part;\n" +
            "<br>ii.                  modify, correct, adapt, translate, enhance or otherwise prepare derivative works or improvements of any Company Intellectual Property or marketing material;\n" +
            "<br>iii.                  rent, lease, lend, sell, sublicense, assign, distribute, publish, transfer or otherwise make available the Services or Route brand to any Person, including on or in connection with the internet or any time-sharing, service bureau, software-as-a-service, cloud or other technology or service;\n" +
            "<br>iv.                  reverse engineer, disassemble, decompile, decode or adapt the services, or otherwise attempt to derive or gain access to the source code or other Intellectual Property associated with the Services, in whole or in part;\n" +
            "<br>v.                  bypass or breach any security device or protection used for or contained in services, intellectual property or marketing material;\n" +
            "<br>vi.                  remove, delete, efface, alter, obscure, translate, combine, supplement or otherwise change any trademarks, terms of use, warranties, disclaimers, or Intellectual Property rights, proprietary rights or other symbols, notices, marks or serial numbers on or relating to any services;\n" +
            "<br>vii.                  use the Intellectual Property or Services in any manner or for any purpose that infringes, misappropriates or otherwise violates any Intellectual Property right or other right of Company or any other Person, or that violates any applicable Law;\n" +
            "<br>viii.                  use the Intellectual Property or Services for purposes of: (i) benchmarking or competitive analysis of the Services; (ii) developing, using or providing a competing product or service; or (iii) any other purpose that is to Company's detriment or commercial disadvantage.\n" +
            "<br>\n" +
            "<br>11.           CONFIDENTIALITY\n" +
            "<br>a.              All non-public, confidential or proprietary information of Company including, but not limited to, specifications, samples, patterns, designs, plans, drawings, documents, data, business operations, customer lists, pricing, discounts or rebates, disclosed by Company to Merchant, whether disclosed orally or disclosed or accessed in written, electronic or other form or media, and whether or not marked, designated or otherwise identified as \"confidential,\" in connection with this Agreement, as well as the terms and conditions and the existence of this Agreement is confidential, solely for the use of performing this Agreement and may not be disclosed or copied unless authorized by Company in writing. Upon Company's request, Merchant shall promptly return all documents and other materials received from Company. Company shall be entitled to injunctive relief for any violation of this Section 11. This section shall not apply to information that is: (a) in the public domain; (b) known to the Merchant at the time of disclosure; or (c) rightfully obtained by the Merchant on a non-confidential basis from a third party.\n" +
            "<br>b.              Merchant agrees that no Confidential Information regarding Company will be used by Merchant in any manner which might be construed by Company to be competitive with or detrimental to its existing or projected business operations.\n" +
            "<br>c.              In the event the receiving party becomes legally compelled to disclose any Information belonging to the disclosing party, the receiving party will provide notice thereof so that the disclosing party may seek a protective order or other appropriate remedy and/or waive compliance with the provisions of this Agreement. In the event that such protective order or other remedy is not obtained, or the disclosing party waives compliance with the provisions of this Agreement, the receiving party shall furnish only that portion of the Confidential Information which is legally required.\n" +
            "<br>d.              This Confidentiality provision shall remain in effect for as long as the Confidential Information remains confidential or until the disclosing party releases the receiving party in writing from its obligations under this Agreement.\n" +
            "<br>\n" +
            "<br>12.           MISCELLANEOUS\n" +
            "<br>a.              Notices.  All notices required or provided under this Agreement shall be in writing, signed by the party giving the same and shall be deemed properly given and received when personally delivered; or upon receipt of a confirmation of transmission by the other party, if sent by facsimile or electronic mail; or five (5) days after deposit in the United Stated first class mail, sent certified or registered, return receipt requested, postage prepaid and addressed to each party’s last known address.\n" +
            "<br>b.              Governing Law.  This Agreement shall be governed by and construed in accordance with the laws of the State of Utah without regard to its conflicts of law’s provisions.\n" +
            "<br>c.              Resolution of Disputes.  Any dispute, controversy or claim arising out of or relating to, this Agreement or breach of this Agreement, or the transactions contemplated hereby, shall be finally settled by arbitration in accordance with the applicable Commercial Arbitration Rules of the American Arbitration Association and judgment upon the award rendered by the arbitrator(s) may be entered in any court having jurisdiction.  Venue for the Arbitration shall be Salt Lake City, Utah.\n" +
            "<br>d.              Attorneys’ Fees.  If any action, suit or other proceeding is instituted concerning or arising out of this Agreement, the prevailing party, or if there be none then the substantially prevailing party, shall recover all of such party’s reasonable costs and attorneys’ fees incurred in each and every such action, suit or other proceeding.\n" +
            "<br>e.              Assignment.  This Agreement may not be assigned or otherwise transferred by either party to third parties without the prior written consent of the other party.\n" +
            "<br>f.               Binding Effect.  This Agreement and the rights, covenants, conditions and obligations of the respective parties hereto and any instrument or agreement executed pursuant hereto shall be binding upon the undersigned and its agents, subsidiaries, affiliates, employees, successors, assigns, and legal representatives.\n" +
            "<br>g.              No Third-Party Beneficiaries. This Agreement is intended for the sole and exclusive benefit of the signatories and is not intended to benefit any third party. Only the parties to this Agreement may enforce it.\n" +
            "<br>h.              Entire Agreement. This Agreement, and any documents attached hereto or incorporated herein by reference, constitute the entire agreement between the parties with respect to the subject matter as contained herein and supersedes all prior and contemporaneous understandings, agreements, representations and warranties both written and oral, with respect to such subject matter.\n" +
            "<br>i.               Amendment.  This Agreement and each of the terms and provisions thereof, can only be amended, emended, modified, waived or supplemented by an agreement in writing signed by each party.\n" +
            "<br>j.               Severability.  In the event any provision of this Agreement is held to be invalid or unenforceable, the remaining provisions of this Agreement shall remain in full force and effect.\n" +
            "<br>k.              Survival. All representations, covenants and warranties shall survive the execution of this Agreement, and Sections 6-8, 10-12 shall survive termination of this Agreement.\n" +
            "<br>l.               Counterparts.  This Agreement may be executed simultaneously in one or more counterparts, each of which shall be deemed an original, but all of which together shall constitute one and the same instrument.";

    public static final String pdfTermsAndConditions = "WHEREAS, Company is in the business of providing merchant services and investigative and remedial solutions and related software to online order problems or failed shipments (collectively, the “Services”) under the brand Route;\n" +
            "\n" +
            "WHEREAS, Merchant operates website(s) offering goods for sale via the Internet; and\n" +
            "\n" +
            "WHEREAS, Merchant desires that Company provide Route-branded Services on selected orders on Merchant’s website(s).\n" +
            "\n" +
            "NOW THEREFORE, in consideration of the mutual promises and covenants hereinafter set forth, the sufficiency of which is hereby acknowledged, Company and Merchant agree as follows:\n" +
            "\n" +
            "1.              SERVICES\n" +
            "a.              During the Term of this Agreement, Merchant agrees to;\n" +
            "i.                  Integration.  Offer Company’s Route-branded Services on Merchant’s website(s), to integrate Company’s API, and to place Route Widget, assets and badges on Merchant’s website(s) checkout page(s), order-confirmation page(s) and emailed order receipt(s) for the purpose of offering Company’s Route Services to Merchant’s customers, as more particularly described in and subject to Company’s terms and conditions.\n" +
            "ii.                  Pricing and Availability or Services.  Offer Company's Services on and only on the pricing terms as set forth in Section 3.\n" +
            "b.              During the term of this Agreement and provided that Merchant continues to offer Company’s Route-branded Services, Company agrees to provide the Services to Merchants' customers subject to the terms and conditions of this Agreement.\n" +
            "\n" +
            "2.              OBLIGATIONS                       During the Term of this Agreement Merchant shall:\n" +
            "a.              Designate one of its employees or agents to serve as its primary contact and to act as its authorized representative with respect to matters pertaining to this Agreement (the \"Merchant Contract Manager\").\n" +
            "b.              Require the Merchant Contract Manager to respond promptly to any reasonable requests from Company for instructions, information or approvals required by Company to provide the Services.\n" +
            "c.              Maintain complete and accurate records relating to the provision of the Services under this Agreement.\n" +
            "d.              Cooperate with Company in its performance of the Services and provide access to Merchant's premises, employees, equipment and business records necessary to enable Company to verify compliance with Route Terms and Conditions and to provide Route Services.\n" +
            "e.              Take all steps necessary, including without limitation obtaining any required licenses or consents, to Maintain Route Merchant Certification and to prevent Merchant-caused delays in Company's provision of the Services.\n" +
            "\n" +
            "3.              PAYMENT\n" +
            "a.              Pricing.    Merchant agrees to set the price of Route Services at $3.97, $4.95, $4.97, or $4.99 per item shipped to Customer, according to Customer’s order.\n" +
            "b.              Revenue.  In consideration of the provision of the Route-branded Services by the Company and the rights granted to Merchant under this Agreement, revenues collected on Route Services sales will be paid out as follows:\n" +
            "i.                  50% of revenues collected will be paid to Company;\n" +
            "ii.                  50% of revenues collected will be retained by Merchant.\n" +
            "c.              Invoicing.  Revenues generated from sales of Route-branded Services will be tracked by Company through Company's API integration with Merchant’s Websites and/or Merchant’s CRM as set forth in Section 1, above.  Company will provide Merchant an accounting invoice of the Route Services revenues via email.\n" +
            "d.              Revenue Disputes.  Merchant will have 24 hours to dispute the accounting report referenced in Section 3.c., above.  At the expiration of 24 hours, the revenues set forth in the applicable report will be deemed final and payment will be due as provided under Section 3.b.i.\n" +
            "e.              Payment Method.  Merchant hereby agrees that, for the term of this Agreement, Company has the right to withdraw Company's payment from Merchant's bank account as provided in the ACH authorization attached hereto as Exhibit B.\n" +
            "f.               Miscellaneous.  Merchant shall be responsible for all sales, use and excise taxes, and any other similar taxes, duties and charges of any kind imposed by any federal, state or local governmental entity on any amounts payable by or to Merchant under this Agreement; provided, that, in no event shall Merchant pay or be responsible for any taxes, duties or charges imposed on, or with respect to, Company's income, or revenues received under this Agreement.\n" +
            "\n" +
            "4.              NO JOINT VENTURE, PARTNERSHIP OR AGENCY                      Except as specifically provided in this Agreement, nothing in this Agreement shall be construed to create a partnership, joint venture or agency relationship between the parties and neither party will have the power to bind the other or to incur obligations on the other’s behalf without such other party’s prior written consent.\n" +
            "\n" +
            "5.              EXCLUSIVITY                         The parties acknowledge and agree that this Agreement shall not be construed to be a commitment by Company to work exclusively with Merchant regarding Company’s Services. Notwithstanding the foregoing, by signing this Agreement, Merchant represents and warrants that during the Term, Merchant will exclusively provide Services from Company and that it will not provide similar Services from any other company.\n" +
            "\n" +
            "6.              REPRESENTATIONS AND WARRANTIES\n" +
            "a.              By Company.   As part of this Agreement, Company represents and warrants that:\n" +
            "i.                  It has the necessary corporate power and authority to enter, carry out its obligations and to grants the rights conferred under this Agreement.\n" +
            "ii.                  It shall perform the Services:\n" +
            "1.     In accordance with the terms and subject to the conditions set out in this Agreement and any applicable, signed statement of services.\n" +
            "2.     Using commercially-reasonable skill, experience and qualifications.\n" +
            "3.     In a timely, workmanlike and professional manner in accordance with generally recognized industry standards for similar services.\n" +
            "b.              By Merchant. As part of this Agreement, Merchant represents and warrants that:\n" +
            "i.                  It has the necessary corporate power and authority to enter into this Agreement, to carry out its obligations hereunder and to grant the rights herein granted;\n" +
            "ii.                  It will conduct business in a manner that reflects favorably on Company and its Services;\n" +
            "iii.                  It will make no false or misleading representations with respect to Company or its services;\n" +
            "iv.                  It will make no representations, warranties, or guarantees with respect to the specifications, features, or capabilities of Company or its Services that are inconsistent with Company’s Marketing Materials.\n" +
            "c.              Mutual.  EXCEPT AS EXPRESSLY SET FORTH HEREIN, TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, EACH PARTY DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT, AND ANY WARRANTIES ARISING OUT OF COURSE OF DEALING OR USAGE OF TRADE.\n" +
            "\n" +
            "7.              INDEMNIFICATION            For and in consideration of Company’s agreements contained herein, Merchant hereby agrees to indemnify each of Company, and its respective partners, members, managers, affiliates, directors, officers, employees, representatives, and agents (each being an “Indemnified Party”), from, and agrees to defend and hold such Indemnified Party harmless against, any and all losses,  liabilities,  charges,  damages, expenses and fees which may be asserted against such Indemnified Party arising out of, resulting from, or related in any way to a breach of any representation, warranty, covenant or agreement of Merchant contained in or made pursuant to this Agreement, or any facts or circumstances surrounding such a breach.\n" +
            "\n" +
            "8.              LIMITATION OF LIABILITY               IN NO EVENT SHALL COMPANY BE LIABLE TO MERCHANT OR TO ANY THIRD PARTY FOR ANY LOSS OF USE, REVENUE OR PROFIT, OR FOR ANY CONSEQUENTIAL, INCIDENTAL, INDIRECT, EXEMPLARY, SPECIAL OR PUNITIVE DAMAGES WHETHER ARISING OUT OF BREACH OF CONTRACT, TORT (INCLUDING NEGLIGENCE) OR OTHERWISE, REGARDLESS OF WHETHER SUCH DAMAGE WAS FORESEEABLE AND WHETHER OR NOT COMPANY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, AND NOTWITHSTANDING THE FAILURE OF ANY AGREED OR OTHER REMEDY OF ITS ESSENTIAL PURPOSE.  IN NO EVENT SHALL COMPANY'S AGGREGATE LIABILITY ARISING OUT OF OR RELATED TO THIS AGREEMENT, WHETHER ARISING OUT OF OR RELATED TO BREACH OF CONTRACT, TORT (INCLUDING NEGLIGENCE) OR OTHERWISE, EXCEED THE AGGREGATE AMOUNTS PAID OR PAYABLE TO COMPANY UNDER THIS AGREEMENT.\n" +
            "\n" +
            "9.              TERM OF AGREEMENT\n" +
            "a.              Term. The term of this Agreement commences on the date of this Agreement and continues for a period of one (1) year, unless and until terminated as provided under this Agreement (the \"Initial Term\"). Upon expiration of the Initial Term, this Agreement automatically renews for additional successive one (1) year terms unless and until either party provides notice of nonrenewal at least thirty (30) days prior to the end of the then-current term, or unless and until earlier terminated as provided under this Agreement (each a \"Renewal Term\" and together with the Initial Term, the \"Term\").\n" +
            "b.              Termination. In addition to any remedies that may be provided in this Agreement, either party may terminate this Agreement with immediate effect upon notice to the other party, if the other party: (i) fails to pay any amount when due under this Agreement and such failure continues for three (3) days after the other party's receipt of notice of nonpayment; (ii) has not otherwise performed or complied with any of the terms of this Agreement, in whole or in part; or (iii) becomes insolvent, files a petition for bankruptcy or commences or has commenced against it proceedings relating to bankruptcy, receivership, reorganization or assignment for the benefit of creditors.\n" +
            "c.              Effect of Termination. On expiration or termination of this Agreement for any reason and subject to any express provisions set out elsewhere in this Agreement:\n" +
            "i.                  all outstanding amounts payable by Merchant to Company shall immediately become due and payable;\n" +
            "ii.                  all express or implied rights granted pursuant to this Agreement shall immediately cease;\n" +
            "iii.                  Merchant shall cease all use of the services, including without limitation the marks, brands, software widget and other Intellectual Property as set forth in sections 1 and 10 herein;\n" +
            "iv.                  Merchant shall promptly return to company, or, at Company's option, destroy, at Merchant's expense, all records and copies of technical and promotional material, including source code if any, in its possession relating to the services, and of any Confidential Information or Intellectual Property of Company and all copies thereof.\n" +
            "\n" +
            "10.           INTELLECTUAL PROPERTY\n" +
            "a.              General.  Company is and shall be the sole owner of all rights, title, patents, copyrights, trademark and other proprietary rights in connection with its Services and no license is granted, assigned or implied to be granted to Merchant by reason of its use of or access to said Services.  Except as set forth in this Agreement or otherwise expressly agreed to in writing by the parties, nothing in this Agreement will be deemed to grant or assign to either party any ownership rights, license rights, or interests of any kind in the other party’s products, services or technology or in the other party’s intellectual property or proprietary rights.\n" +
            "b.              Marketing Materials.  From time to time, Company will provide Merchant with its standard marketing and sales literature that it customarily uses to promote Company’s Services (“Marketing Materials”). Merchant will use Company’s Marketing Materials solely for the purposes of this Agreement. Merchant may not copy, modify, alter, adapt or create derivative works based on Company’s Marketing Materials.\n" +
            "c.              Use Restrictions. Except as this Agreement expressly permits Merchant shall not, and shall not permit any other Person to:\n" +
            "i.                  copy the Company's Services, Intellectual Property or marketing material, in whole or in part;\n" +
            "ii.                  modify, correct, adapt, translate, enhance or otherwise prepare derivative works or improvements of any Company Intellectual Property or marketing material;\n" +
            "iii.                  rent, lease, lend, sell, sublicense, assign, distribute, publish, transfer or otherwise make available the Services or Route brand to any Person, including on or in connection with the internet or any time-sharing, service bureau, software-as-a-service, cloud or other technology or service;\n" +
            "iv.                  reverse engineer, disassemble, decompile, decode or adapt the services, or otherwise attempt to derive or gain access to the source code or other Intellectual Property associated with the Services, in whole or in part;\n" +
            "v.                  bypass or breach any security device or protection used for or contained in services, intellectual property or marketing material;\n" +
            "vi.                  remove, delete, efface, alter, obscure, translate, combine, supplement or otherwise change any trademarks, terms of use, warranties, disclaimers, or Intellectual Property rights, proprietary rights or other symbols, notices, marks or serial numbers on or relating to any services;\n" +
            "vii.                  use the Intellectual Property or Services in any manner or for any purpose that infringes, misappropriates or otherwise violates any Intellectual Property right or other right of Company or any other Person, or that violates any applicable Law;\n" +
            "viii.                  use the Intellectual Property or Services for purposes of: (i) benchmarking or competitive analysis of the Services; (ii) developing, using or providing a competing product or service; or (iii) any other purpose that is to Company's detriment or commercial disadvantage.\n" +
            "\n" +
            "11.           CONFIDENTIALITY\n" +
            "a.              All non-public, confidential or proprietary information of Company including, but not limited to, specifications, samples, patterns, designs, plans, drawings, documents, data, business operations, customer lists, pricing, discounts or rebates, disclosed by Company to Merchant, whether disclosed orally or disclosed or accessed in written, electronic or other form or media, and whether or not marked, designated or otherwise identified as \"confidential,\" in connection with this Agreement, as well as the terms and conditions and the existence of this Agreement is confidential, solely for the use of performing this Agreement and may not be disclosed or copied unless authorized by Company in writing. Upon Company's request, Merchant shall promptly return all documents and other materials received from Company. Company shall be entitled to injunctive relief for any violation of this Section 11. This section shall not apply to information that is: (a) in the public domain; (b) known to the Merchant at the time of disclosure; or (c) rightfully obtained by the Merchant on a non-confidential basis from a third party.\n" +
            "b.              Merchant agrees that no Confidential Information regarding Company will be used by Merchant in any manner which might be construed by Company to be competitive with or detrimental to its existing or projected business operations.\n" +
            "c.              In the event the receiving party becomes legally compelled to disclose any Information belonging to the disclosing party, the receiving party will provide notice thereof so that the disclosing party may seek a protective order or other appropriate remedy and/or waive compliance with the provisions of this Agreement. In the event that such protective order or other remedy is not obtained, or the disclosing party waives compliance with the provisions of this Agreement, the receiving party shall furnish only that portion of the Confidential Information which is legally required.\n" +
            "d.              This Confidentiality provision shall remain in effect for as long as the Confidential Information remains confidential or until the disclosing party releases the receiving party in writing from its obligations under this Agreement.\n" +
            "\n" +
            "12.           MISCELLANEOUS\n" +
            "a.              Notices.  All notices required or provided under this Agreement shall be in writing, signed by the party giving the same and shall be deemed properly given and received when personally delivered; or upon receipt of a confirmation of transmission by the other party, if sent by facsimile or electronic mail; or five (5) days after deposit in the United Stated first class mail, sent certified or registered, return receipt requested, postage prepaid and addressed to each party’s last known address.\n" +
            "b.              Governing Law.  This Agreement shall be governed by and construed in accordance with the laws of the State of Utah without regard to its conflicts of law’s provisions.\n" +
            "c.              Resolution of Disputes.  Any dispute, controversy or claim arising out of or relating to, this Agreement or breach of this Agreement, or the transactions contemplated hereby, shall be finally settled by arbitration in accordance with the applicable Commercial Arbitration Rules of the American Arbitration Association and judgment upon the award rendered by the arbitrator(s) may be entered in any court having jurisdiction.  Venue for the Arbitration shall be Salt Lake City, Utah.\n" +
            "d.              Attorneys’ Fees.  If any action, suit or other proceeding is instituted concerning or arising out of this Agreement, the prevailing party, or if there be none then the substantially prevailing party, shall recover all of such party’s reasonable costs and attorneys’ fees incurred in each and every such action, suit or other proceeding.\n" +
            "e.              Assignment.  This Agreement may not be assigned or otherwise transferred by either party to third parties without the prior written consent of the other party.\n" +
            "f.               Binding Effect.  This Agreement and the rights, covenants, conditions and obligations of the respective parties hereto and any instrument or agreement executed pursuant hereto shall be binding upon the undersigned and its agents, subsidiaries, affiliates, employees, successors, assigns, and legal representatives.\n" +
            "g.              No Third-Party Beneficiaries. This Agreement is intended for the sole and exclusive benefit of the signatories and is not intended to benefit any third party. Only the parties to this Agreement may enforce it.\n" +
            "h.              Entire Agreement. This Agreement, and any documents attached hereto or incorporated herein by reference, constitute the entire agreement between the parties with respect to the subject matter as contained herein and supersedes all prior and contemporaneous understandings, agreements, representations and warranties both written and oral, with respect to such subject matter.\n" +
            "i.               Amendment.  This Agreement and each of the terms and provisions thereof, can only be amended, emended, modified, waived or supplemented by an agreement in writing signed by each party.\n" +
            "j.               Severability.  In the event any provision of this Agreement is held to be invalid or unenforceable, the remaining provisions of this Agreement shall remain in full force and effect.\n" +
            "k.              Survival. All representations, covenants and warranties shall survive the execution of this Agreement, and Sections 6-8, 10-12 shall survive termination of this Agreement.\n" +
            "l.               Counterparts.  This Agreement may be executed simultaneously in one or more counterparts, each of which shall be deemed an original, but all of which together shall constitute one and the same instrument.";
}
