package core.services;

import org.springframework.stereotype.Service;

import java.util.LinkedHashMap;
import java.util.Map;

@Service
public class RegisterFormService {

    public Map<String,String> transactionOptions() {
        Map<String,String> transactions = new LinkedHashMap<>();
        transactions.put("50","0-50");
        transactions.put("100","50-100");
        transactions.put("500","100-500");
        transactions.put("1000","500-1,000");
        transactions.put("1001","1,000+");
        return transactions;
    }

    public Map<String,String> crmOptions() {
        Map<String,String> crms = new LinkedHashMap<String, String>();
        crms.put("","-- Select One --");
        crms.put("Konnektive","Konnektive");
        crms.put("LimeLight","LimeLight");
        crms.put("3dcart","3dcart");
        crms.put("AceShop","AceShop");
        crms.put("ASP dot net Storefront","ASP dot net Storefront");
        crms.put("Big Commerce","Big Commerce");
        crms.put("Loaded Commerce","Loaded Commerce");
        crms.put("CS-Cart","CS-Cart");
        crms.put("Cube Cart","Cube Cart");
        crms.put("Gamblo","Gamblo");
        crms.put("Interspire","Interspire");
        crms.put("JooCart","JooCart");
        crms.put("LemonStand","LemonStand");
        crms.put("Magento","Magento");
        crms.put("Magento2","Magento2");
        crms.put("MijoShop","MijoShop");
        crms.put("MobiCart","MobiCart");
        crms.put("OpenCart","OpenCart");
        crms.put("osCmax","osCmax");
        crms.put("osCommerce","osCommerce");
        crms.put("Orange","Orange");
        crms.put("OXID eSales","OXID eSales");
        crms.put("PinnacleCart","PinnacleCart");
        crms.put("PrestaShop","PrestaShop");
        crms.put("Shop-Script","Shop-Script");
        crms.put("Shopify","Shopify");
        crms.put("Shopware","Shopware");
        crms.put("Tomato Cart","Tomato Cart");
        crms.put("Triangle","Triangle");
        crms.put("Ubercart","Ubercart");
        crms.put("UltraCart","UltraCart");
        crms.put("VirtueMart","VirtueMart");
        crms.put("Volusion","Volusion");
        crms.put("WP e-Commerce","WP e-Commerce");
        crms.put("Webasyst","Webasyst");
        crms.put("WooCommerce","WooCommerce");
        crms.put("XCART","XCART");
        crms.put("xt:Commerce","xt:Commerce");
        crms.put("xt:Commerce VEYTON","xt:Commerce VEYTON");
        crms.put("Zencart","Zencart");
        crms.put("other","other");
        return crms;
    }

    public Map<String,String> crmOtherOptions() {
        Map<String,String> otherCrms = new LinkedHashMap<String, String>();
        otherCrms.put("","-- Select One --");
        otherCrms.put("Marketing360","Marketing 360");
        otherCrms.put("Freshdesk","Freshdesk");
        otherCrms.put("Pipedrive","Pipedrive");
        otherCrms.put("Insightly","Insightly");
        otherCrms.put("SalesforceIQ","SalesforceIQ");
        otherCrms.put("Infusionsoft","Infusionsoft");
        otherCrms.put("ConnectWisePSA","ConnectWise PSA");
        otherCrms.put("BullhornCRM","Bullhorn CRM");
        otherCrms.put("NetSuiteCRM+","NetSuite CRM+");
        otherCrms.put("Logicbox","Logicbox");
        otherCrms.put("DayliteforMac","Daylite for Mac");
        otherCrms.put("InfoFlo","InfoFlo");
        otherCrms.put("LessAnnoyingCRM","Less Annoying CRM");
        otherCrms.put("SupportCenterPlus","SupportCenter Plus");
        otherCrms.put("ClaritysoftCRM","Claritysoft CRM");
        otherCrms.put("PipelinerCRM","Pipeliner CRM");
        otherCrms.put("ZohoCRM","Zoho CRM");
        otherCrms.put("DoximCRM","Doxim CRM");
        otherCrms.put("W3BCRM","W3B CRM");
        otherCrms.put("AuricProspector","Auric Prospector");
        otherCrms.put("InsideSalesBox","Inside Sales Box");
        otherCrms.put("MethodCRM","Method CRM");
        otherCrms.put("ReallySimple","Really Simple Systems CRM");
        otherCrms.put("ApptivoCRM","Apptivo CRM");
        otherCrms.put("RepslyMobile","Repsly Mobile CRM");
        otherCrms.put("Salesforce","Salesforce");
        otherCrms.put("HubSpot","HubSpot CRM");
        otherCrms.put("Blitz","Blitz");
        otherCrms.put("PayPanther","PayPanther");
        otherCrms.put("Teamgate","Teamgate");
        otherCrms.put("InStream","InStream");
        otherCrms.put("DSS","DSS");
        otherCrms.put("RepairShopr","RepairShopr");
        otherCrms.put("SalesJunction","SalesJunction");
        otherCrms.put("Salesbox","Salesbox");
        otherCrms.put("Nutshell","Nutshell");
        otherCrms.put("Highrise","Highrise");
        otherCrms.put("karma","karmaCRM");
        otherCrms.put("ProsperWorks","ProsperWorks CRM");
        otherCrms.put("RAYNET","RAYNET CRM");
        otherCrms.put("Bitochon","Bitochon CRM");
        otherCrms.put("Act","Act!");
        otherCrms.put("amoCRM","amoCRM");
        otherCrms.put("Blazedesk","Blazedesk");
        otherCrms.put("OnePage","OnePageCRM");
        otherCrms.put("FieldForce","FieldForce");
        otherCrms.put("Bitrix24","Bitrix24");
        otherCrms.put("Snapforce","Snapforce CRM");
        otherCrms.put("Commence","Commence");
        otherCrms.put("Data2CRM","Data2CRM.Migration");
        otherCrms.put("SalesNexus","SalesNexus Online CRM");
        otherCrms.put("CustomAnswers","CustomAnswers");
        otherCrms.put("Tubular","Tubular");
        otherCrms.put("Accelo","Accelo");
        otherCrms.put("Desk","Desk.com");
        otherCrms.put("SanityOS","SanityOS");
        otherCrms.put("MarketingEssentials","Marketing Essentials");
        otherCrms.put("AgentCubed","AgentCubed");
        otherCrms.put("SugarCRM","SugarCRM");
        otherCrms.put("vtiger","vtiger CRM");
        otherCrms.put("Colabo","Colabo");
        otherCrms.put("Comidor","Comidor");
        otherCrms.put("GoldVision","Gold-Vision CRM");
        otherCrms.put("OnDemand","On Demand CRM");
        otherCrms.put("Contactually","Contactually");
        otherCrms.put("SalezShark","SalezShark");
        otherCrms.put("Salesnet","Salesnet CRM");
        otherCrms.put("webCRM","webCRM");
        otherCrms.put("SalesBabu","SalesBabu CRM");
        otherCrms.put("Base","Base");
        otherCrms.put("Bluwave","Bluwave CRM");
        otherCrms.put("C2CRM","C2CRM");
        otherCrms.put("Capsule","Capsule");
        otherCrms.put("Closeio","Close.io");
        otherCrms.put("COMPLETExRM","COMPLETExRM");
        otherCrms.put("Composity","Composity");
        otherCrms.put("onclouds","Crm on clouds");
        otherCrms.put("Erpisto","Erpisto CRM");
        otherCrms.put("HyperTeamCRM","HyperTeam CRM for Office 365");
        otherCrms.put("ilinked","i-linked");
        otherCrms.put("PeopleVine","PeopleVine");
        otherCrms.put("Rainbow","Rainbow CRM");
        otherCrms.put("ResultsSuite","Results CRM & Business Suite");
        otherCrms.put("Soffront","Soffront CRM");
        otherCrms.put("Triumph","TriumphCRM");
        otherCrms.put("Dynamics","Dynamics CRM");
        otherCrms.put("Raw","Raw CRM");
        otherCrms.put("eWay","eWay-CRM");
        otherCrms.put("Streak","Streak");
        otherCrms.put("Talisma","Talisma CRM");
        otherCrms.put("OMNITRACKER","OMNITRACKER");
        otherCrms.put("CRMPRO","CRMPRO");
        otherCrms.put("1CRM","1CRM");
        otherCrms.put("360Suite","360 Enterprise Suite");
        otherCrms.put("Aicon","Aicon CRM");
        otherCrms.put("Aplicor","Aplicor 3C");
        otherCrms.put("Assimilate","Assimilate");
        otherCrms.put("Automational","Automational");
        otherCrms.put("Batchbook","Batchbook");
        otherCrms.put("CallCenterCRM","Call Center CRM");
        otherCrms.put("CallPro","CallPro CRM");
        otherCrms.put("Clevertim","Clevertim CRM");
        otherCrms.put("CloudYogi","CloudYogi CRM");
        otherCrms.put("CompanyHub","CompanyHub");
        otherCrms.put("ConvergeHub","ConvergeHub");
        otherCrms.put("CRM","CRM");
        otherCrms.put("CRMnext","CRMnext");
        otherCrms.put("DealCloud","DealCloud");
        otherCrms.put("Efficy","Efficy CRM");
        otherCrms.put("eSalesTrack","eSalesTrack CRM");
        otherCrms.put("eZnet","eZnet CRM");
        otherCrms.put("Futurelabs","Futurelabs CRM");
        otherCrms.put("GetScorecard","GetScorecard");
        otherCrms.put("Interakt","Interakt");
        otherCrms.put("itracEMS","itracEMS");
        otherCrms.put("Kapture","Kapture CRM");
        otherCrms.put("KulaHub","KulaHub");
        otherCrms.put("LeadTrac","LeadTrac");
        otherCrms.put("LIID","LIID for Salesforce");
        otherCrms.put("ListMaster","List Master CRM");
        otherCrms.put("Lunar","Lunar CRM");
        otherCrms.put("Mothernode","Mothernode CRM");
        otherCrms.put("SalesDialer","My Sales Dialer");
        otherCrms.put("MyBusiness","MyBusiness");
        otherCrms.put("NOWTIS","NOWTIS");
        otherCrms.put("Pepperi","Pepperi");
        otherCrms.put("PlanPlus","PlanPlus CRM");
        otherCrms.put("ProspectSleuth","Prospect Sleuth CRM");
        otherCrms.put("Push","Push It");
        otherCrms.put("Radium","Radium CRM");
        otherCrms.put("Saarif","Saarif CRM");
        otherCrms.put("SalesNOW","SalesNOW");
        otherCrms.put("SAP","SAP CRM");
        otherCrms.put("Sextant","Sextant CRM");
        otherCrms.put("Skyward","Skyward CRM");
        otherCrms.put("SoulCRM","SoulCRM");
        otherCrms.put("Suntico ","Suntico ");
        otherCrms.put("SuperOffice","SuperOffice CRM");
        otherCrms.put("Telenotes","Telenotes CRM");
        otherCrms.put("WiredContact","WiredContact Enterprise");
        otherCrms.put("Amphis","Amphis Customer");
        otherCrms.put("Atemis","Atemis CRM");
        otherCrms.put("CXM","CXM");
        otherCrms.put("Deskera","Deskera CRM");
        otherCrms.put("Leads365","Leads 365");
        otherCrms.put("Maximizer","Maximizer CRM");
        otherCrms.put("PharmaCODE","PharmaCODE");
        otherCrms.put("Saleswah","Saleswah CRM");
        otherCrms.put("SuiteCRM","SuiteCRM");
        otherCrms.put("Winds","Winds CRM");
        otherCrms.put("AppShore","AppShore");
        otherCrms.put("PRIAM","PRIAM ERP/CRM");
        otherCrms.put("AllProWebTools","AllProWebTools");
        otherCrms.put("Routzy","Routzy");
        otherCrms.put("SalesOutlook","SalesOutlook CRM");
        otherCrms.put("3GBusiness","3GBusiness");
        otherCrms.put("4ASoft","4ASoft Agenda");
        otherCrms.put("90degree","90degree Team Task");
        otherCrms.put("ClientCare","AB Client Care");
        otherCrms.put("absoluteBUSY","absoluteBUSY");
        otherCrms.put("ACEManager","ACE Contact Manager");
        otherCrms.put("Achiever","Achiever CRM");
        otherCrms.put("ADAPTcrm","ADAPTcrm");
        otherCrms.put("adeptcrmsales","adeptcrmsales");
        otherCrms.put("Affinity","Affinity");
        otherCrms.put("AgencyOrganizer","AgencyOrganizer");
        otherCrms.put("Agendize","Agendize");
        otherCrms.put("AgentGovCon","Agent GovCon");
        otherCrms.put("Agile","Agile CRM");
        otherCrms.put("ALBXSolution","ALBX CRM Solution");
        otherCrms.put("Align","Align");
        otherCrms.put("AllClients","AllClients");
        otherCrms.put("AmdocsCustomerManagement","Amdocs Customer Management");
        otherCrms.put("Amisha","Amisha");
        otherCrms.put("ApisCRM","Apis CRM");
        otherCrms.put("AppStacks","AppStacks CRM");
        otherCrms.put("APTEAN","APTEAN CRM");
        otherCrms.put("AquaCRM","AquaCRM");
        otherCrms.put("Ardexus","Ardexus WebMODE CRM");
        otherCrms.put("AutoRaptor","AutoRaptor CRM");
        otherCrms.put("Avature","Avature");
        otherCrms.put("Avidian","Avidian");
        otherCrms.put("B2iCRM","B2i CRM");
        otherCrms.put("BasicOnline","Basic Online CRM");
        otherCrms.put("bCommunities","bCommunities");
        otherCrms.put("bexio","bexio");
        otherCrms.put("Billing System","Billing System");
        otherCrms.put("Bios CRM","Bios CRM");
        otherCrms.put("Bizzy","Bizzy");
        otherCrms.put("BlueCamroo","BlueCamroo");
        otherCrms.put("BlueRobin CRM","BlueRobin CRM");
        otherCrms.put("Borneosoft Online Forms & CRM","Borneosoft Online Forms & CRM");
        otherCrms.put("BPA CRM","BPA CRM");
        otherCrms.put("bpm'online CRM","bpm'online CRM");
        otherCrms.put("BusinessMan Enterprise","BusinessMan Enterprise");
        otherCrms.put("BuzzFlow","BuzzFlow");
        otherCrms.put("CampaignerCRM","CampaignerCRM");
        otherCrms.put("Capriccio Fuzion","Capriccio Fuzion");
        otherCrms.put("Catalyst","Catalyst");
        otherCrms.put("Cendyn/One","Cendyn/One");
        otherCrms.put("Centerbase","Centerbase");
        otherCrms.put("CentralStationCRM","CentralStationCRM");
        otherCrms.put("Cirrus Insight","Cirrus Insight");
        otherCrms.put("Client Book CRM","Client Book CRM");
        otherCrms.put("ClientLogix","ClientLogix");
        otherCrms.put("ClientSpace","ClientSpace");
        otherCrms.put("CLIM8.NET","CLIM8.NET");
        otherCrms.put("Clintra","Clintra");
        otherCrms.put("CMPro Plus","CMPro Plus");
        otherCrms.put("CollaBrill","CollaBrill");
        otherCrms.put("Comarch CRM for Telecoms","Comarch CRM for Telecoms");
        otherCrms.put("ConcourseSuite","ConcourseSuite");
        otherCrms.put("Connector","Connector");
        otherCrms.put("Conrep","Conrep");
        otherCrms.put("ContactEase","ContactEase");
        otherCrms.put("Conversocial","Conversocial");
        otherCrms.put("Cool Life CRM","Cool Life CRM");
        otherCrms.put("Core3 CRM","Core3 CRM");
        otherCrms.put("CounterBalance","CounterBalance");
        otherCrms.put("cRM","cRM");
        otherCrms.put("CRM and ERP Software","CRM and ERP Software");
        otherCrms.put("CRM Billing Software","CRM Billing Software");
        otherCrms.put("CRM Express","CRM Express");
        otherCrms.put("CRM Plus","CRM Plus");
        otherCrms.put("CRM Project Manager","CRM Project Manager");
        otherCrms.put("CRM software","CRM software");
        otherCrms.put("CRM Software","CRM Software");
        otherCrms.put("CRM-Express","CRM-Express");
        otherCrms.put("CRM-gx","CRM-gx");
        otherCrms.put("CRM24x7","CRM24x7");
        otherCrms.put("CRMadar","CRMadar");
        otherCrms.put("CRMBOOST","CRMBOOST");
        otherCrms.put("CRMGRID","CRMGRID");
        otherCrms.put("CRMlet","CRMlet");
        otherCrms.put("CRMrus","CRMrus");
        otherCrms.put("CrowdTwist","CrowdTwist");
        otherCrms.put("Customer Relationship Manager","Customer Relationship Manager");
        otherCrms.put("CustomerFirst","CustomerFirst");
        otherCrms.put("CVenture ","CVenture ");
        otherCrms.put("CxCRM","CxCRM");
        otherCrms.put("CXRM","CXRM");
        otherCrms.put("Daxko Engage","Daxko Engage");
        otherCrms.put("Deltek Vision","Deltek Vision");
        otherCrms.put("DotAlign for Outlook","DotAlign for Outlook");
        otherCrms.put("E-DEAL CRM","E-DEAL CRM");
        otherCrms.put("Easy Simple CRM","Easy Simple CRM");
        otherCrms.put("Elements CRM","Elements CRM");
        otherCrms.put("EnquireLEADS","EnquireLEADS");
        otherCrms.put("ePowerCenter","ePowerCenter");
        otherCrms.put("ERP-ONE","ERP-ONE");
        otherCrms.put("EspoCRM","EspoCRM");
        otherCrms.put("eWebLife","eWebLife");
        otherCrms.put("eXcediant","eXcediant");
        otherCrms.put("eXert CRM","eXert CRM");
        otherCrms.put("EXPERT Mobile Agent","EXPERT Mobile Agent");
        otherCrms.put("eZnet CRM","eZnet CRM");
        otherCrms.put("FastTrack","FastTrack");
        otherCrms.put("Fat Free CRM","Fat Free CRM");
        otherCrms.put("FernCRM","FernCRM");
        otherCrms.put("FileMaker Pro App for CRM","FileMaker Pro App for CRM");
        otherCrms.put("Flightdeck","Flightdeck");
        otherCrms.put("Flowlens","Flowlens");
        otherCrms.put("Focus CRM","Focus CRM");
        otherCrms.put("Forcemanager","Forcemanager");
        otherCrms.put("FPS GOLD Relationship Management","FPS GOLD Relationship Management");
        otherCrms.put("Freshsales","Freshsales");
        otherCrms.put("FundEngine","FundEngine");
        otherCrms.put("Gift and Loyalty","Gift and Loyalty");
        otherCrms.put("Gifttag","Gifttag");
        otherCrms.put("Globitel Retail Quality Management (RQM)","Globitel Retail Quality Management (RQM)");
        otherCrms.put("GoldMine","GoldMine");
        otherCrms.put("GreenRope","GreenRope");
        otherCrms.put("gxCommerce","gxCommerce");
        otherCrms.put("Healthcare CRM","Healthcare CRM");
        otherCrms.put("Heap","Heap");
        otherCrms.put("HyperOffice CRM","HyperOffice CRM");
        otherCrms.put("icomplete","icomplete");
        otherCrms.put("iGlobe CRM for Office 365","iGlobe CRM for Office 365");
        otherCrms.put("iGov CRM","iGov CRM");
        otherCrms.put("Impel CRM","Impel CRM");
        otherCrms.put("InfiniteCRM","InfiniteCRM");
        otherCrms.put("Infor CRM","Infor CRM");
        otherCrms.put("Infor CRM","Infor CRM");
        otherCrms.put("InfoServ","InfoServ");
        otherCrms.put("Inigo","Inigo");
        otherCrms.put("Insight Selling Suite","Insight Selling Suite");
        otherCrms.put("IntelliPad CRM","IntelliPad CRM");
        otherCrms.put("Intellistant","Intellistant");
        otherCrms.put("Interneer Intellect","Interneer Intellect");
        otherCrms.put("InTimeCRM","InTimeCRM");
        otherCrms.put("InTouch","InTouch");
        otherCrms.put("InvisibleCRM","InvisibleCRM");
        otherCrms.put("ioGrow","ioGrow");
        otherCrms.put("IRIS CRM","IRIS CRM");
        otherCrms.put("ITISL CRM","ITISL CRM");
        otherCrms.put("Juggernaut CRM","Juggernaut CRM");
        otherCrms.put("junariCRM","junariCRM");
        otherCrms.put("Junxure Cloud","Junxure Cloud");
        otherCrms.put("Kahoots App","Kahoots App");
        otherCrms.put("KasCur Pro CRM","KasCur Pro CRM");
        otherCrms.put("KEA","KEA");
        otherCrms.put("KeiCRM","KeiCRM");
        otherCrms.put("Kool CRM","Kool CRM");
        otherCrms.put("LAMP-360","LAMP-360");
        otherCrms.put("LeadOrganizer","LeadOrganizer");
        otherCrms.put("Legrand CRM","Legrand CRM");
        otherCrms.put("Lighthouse CRM","Lighthouse CRM");
        otherCrms.put("LIME Easy","LIME Easy");
        otherCrms.put("LinkPoint Connect","LinkPoint Connect");
        otherCrms.put("Logical Office","Logical Office");
        otherCrms.put("LogicBright CRM","LogicBright CRM");
        otherCrms.put("Luxor CRM","Luxor CRM");
        otherCrms.put("M R Reporting Software","M R Reporting Software");
        otherCrms.put("MagicCRM","MagicCRM");
        otherCrms.put("MAP.CRM","MAP.CRM");
        otherCrms.put("MasterSales","MasterSales");
        otherCrms.put("MasterStream","MasterStream");
        otherCrms.put("MaxiClient CRM","MaxiClient CRM");
        otherCrms.put("melssCRM","melssCRM");
        otherCrms.put("MergeWare CRM","MergeWare CRM");
        otherCrms.put("MGW CRM","MGW CRM");
        otherCrms.put("MiAgent","MiAgent");
        otherCrms.put("MicroCRM","MicroCRM");
        otherCrms.put("Mioclient","Mioclient");
        otherCrms.put("Mobilize","Mobilize");
        otherCrms.put("Money Advice + CRM","Money Advice + CRM");
        otherCrms.put("NEHANET CRM","NEHANET CRM");
        otherCrms.put("Neofive Customer Portal","Neofive Customer Portal");
        otherCrms.put("netPeople","netPeople");
        otherCrms.put("Nimble","Nimble");
        otherCrms.put("Nutriadmin","Nutriadmin");
        otherCrms.put("OI CRM","OI CRM");
        otherCrms.put("OM.Net","OM.Net");
        otherCrms.put("ONDiGO","ONDiGO");
        otherCrms.put("OneSource","OneSource");
        otherCrms.put("Online CRM Software","Online CRM Software");
        otherCrms.put("OpenCRM","OpenCRM");
        otherCrms.put("openCRX","openCRX");
        otherCrms.put("Oracle CRM","Oracle CRM");
        otherCrms.put("Oracle Sales Cloud","Oracle Sales Cloud");
        otherCrms.put("OroCRM","OroCRM");
        otherCrms.put("Oscar","Oscar");
        otherCrms.put("Outfield","Outfield");
        otherCrms.put("Pega CRM","Pega CRM");
        otherCrms.put("Peppercan","Peppercan");
        otherCrms.put("PerformYard Sales","PerformYard Sales");
        otherCrms.put("PlayMaker CRM","PlayMaker CRM");
        otherCrms.put("Plum CRM","Plum CRM");
        otherCrms.put("PMAM CRM","PMAM CRM");
        otherCrms.put("Project Pipeline","Project Pipeline");
        otherCrms.put("Pronto Xi Sales & Marketing","Pronto Xi Sales & Marketing");
        otherCrms.put("ProSTART 2013","ProSTART 2013");
        otherCrms.put("QuickBase","QuickBase");
        otherCrms.put("QuickDesk","QuickDesk");
        otherCrms.put("QuinataCRM","QuinataCRM");
        otherCrms.put("Qwikkr","Qwikkr");
        otherCrms.put("RealTime CRM","RealTime CRM");
        otherCrms.put("Rebilly","Rebilly");
        otherCrms.put("Reflect","Reflect");
        otherCrms.put("Relay","Relay");
        otherCrms.put("Relenta","Relenta");
        otherCrms.put("Resco Mobile CRM","Resco Mobile CRM");
        otherCrms.put("REST","REST");
        otherCrms.put("retailCRM","retailCRM");
        otherCrms.put("REthink","REthink");
        otherCrms.put("Revamp CRM","Revamp CRM");
        otherCrms.put("RevenueBee","RevenueBee");
        otherCrms.put("Ricochet","Ricochet");
        otherCrms.put("Riptide Cloud","Riptide Cloud");
        otherCrms.put("Rubi CRM","Rubi CRM");
        otherCrms.put("Ryan Solutions","Ryan Solutions");
        otherCrms.put("Sage CRM","Sage CRM");
        otherCrms.put("SalesAchiever Construction CRM","SalesAchiever Construction CRM");
        otherCrms.put("SalesBase CRM","SalesBase CRM");
        otherCrms.put("Salesforce Marketing Cloud","Salesforce Marketing Cloud");
        otherCrms.put("Salesformics","Salesformics");
        otherCrms.put("SalesGrow","SalesGrow");
        otherCrms.put("SalesIn4 CRM","SalesIn4 CRM");
        otherCrms.put("SalesMesh","SalesMesh");
        otherCrms.put("SalesMetric","SalesMetric");
        otherCrms.put("SalesOptima Stratus","SalesOptima Stratus");
        otherCrms.put("SalesOptimize","SalesOptimize");
        otherCrms.put("SalesPage","SalesPage");
        otherCrms.put("SalesPredict","SalesPredict");
        otherCrms.put("SalesRadar","SalesRadar");
        otherCrms.put("SalesSeek","SalesSeek");
        otherCrms.put("Salestrakr CRM","Salestrakr CRM");
        otherCrms.put("Saleswit Pinnate","Saleswit Pinnate");
        otherCrms.put("SAP Beyond CRM","SAP Beyond CRM");
        otherCrms.put("SAP Digital CRM","SAP Digital CRM");
        otherCrms.put("SAS Customer Intelligence","SAS Customer Intelligence");
        otherCrms.put("Second CRM","Second CRM");
        otherCrms.put("SEI CRM","SEI CRM");
        otherCrms.put("Sellf CRM","Sellf CRM");
        otherCrms.put("Sellsy","Sellsy");
        otherCrms.put("SignupLab","SignupLab");
        otherCrms.put("Simple Sales Tracking","Simple Sales Tracking");
        otherCrms.put("SimpleCRM","SimpleCRM");
        otherCrms.put("simpleview CRM","simpleview CRM");
        otherCrms.put("Simplicity CRM","Simplicity CRM");
        otherCrms.put("Simply CRM","Simply CRM");
        otherCrms.put("SIS CRM","SIS CRM");
        otherCrms.put("SkyCRM","SkyCRM");
        otherCrms.put("SmartCompany","SmartCompany");
        otherCrms.put("SmarterSMB","SmarterSMB");
        otherCrms.put("SmartOffice","SmartOffice");
        otherCrms.put("SmartRoom CRM","SmartRoom CRM");
        otherCrms.put("SmartStart CRM","SmartStart CRM");
        otherCrms.put("SmartTouch CRM","SmartTouch CRM");
        otherCrms.put("SnapCRM","SnapCRM");
        otherCrms.put("Sobia Canyon","Sobia Canyon");
        otherCrms.put("SP CRM Lite","SP CRM Lite");
        otherCrms.put("Sparkcentral Customer Engagement Platform","Sparkcentral Customer Engagement Platform");
        otherCrms.put("SplendidCRM Enterprise","SplendidCRM Enterprise");
        otherCrms.put("SprinxCRM","SprinxCRM");
        otherCrms.put("StarterCRM","StarterCRM");
        otherCrms.put("StayinFront TouchRX","StayinFront TouchRX");
        otherCrms.put("SwiftCRM","SwiftCRM");
        otherCrms.put("Swyft Interaction Hub","Swyft Interaction Hub");
        otherCrms.put("T3 CRM","T3 CRM");
        otherCrms.put("Tabillo","Tabillo");
        otherCrms.put("Tactile CRM","Tactile CRM");
        otherCrms.put("Talisma CRM","Talisma CRM");
        otherCrms.put("TangoCRM","TangoCRM");
        otherCrms.put("TCS CRM","TCS CRM");
        otherCrms.put("Teamleader","Teamleader");
        otherCrms.put("Techsysplus CRM","Techsysplus CRM");
        otherCrms.put("Teckst","Teckst");
        otherCrms.put("TLD CRM","TLD CRM");
        otherCrms.put("Tour de Force CRM","Tour de Force CRM");
        otherCrms.put("TrackerGO CRM","TrackerGO CRM");
        otherCrms.put("Tuo Dynamics CRM","Tuo Dynamics CRM");
        otherCrms.put("Tustena CRM","Tustena CRM");
        otherCrms.put("Ultra-Staff Software","Ultra-Staff Software");
        otherCrms.put("update.CRM","update.CRM");
        otherCrms.put("Veeva CRM","Veeva CRM");
        otherCrms.put("Veloxy","Veloxy");
        otherCrms.put("Viabl","Viabl");
        otherCrms.put("Vite CRM","Vite CRM");
        otherCrms.put("VTC CRM","VTC CRM");
        otherCrms.put("WakeUpSales","WakeUpSales");
        otherCrms.put("Wintouch eCRM","Wintouch eCRM");
        otherCrms.put("WizSame","WizSame");
        otherCrms.put("ysura","ysura");
        otherCrms.put("ZeyOS","ZeyOS");
        otherCrms.put("ZIRA CRM","ZIRA CRM");
        otherCrms.put("Zurmo","Zurmo");
        otherCrms.put("Zyprr","Zyprr");
        return otherCrms;
    }
}
